version: "2.4"
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        env_file:
            - .env
        volumes:
         - ./mysql_data:/var/lib/mysql
        restart: unless-stopped
    server:
        build:
            context: ./server
        env_file:
            - .env
        restart: unless-stopped
        ports:
            -  8080:26560
    client:
        build:
            context: ./client
        env_file:
            - .env
        restart: unless-stopped
        ports:
            - 80:5000